### ISSUE TITLE
Web Interface

### ISSUE THREAD

**Issue by fluential** [jakiestfu/off-the-rip#5]
It would be nice to have web interface, as a free and opensource alternative for http://anything2mp3.com/

**Comment by jazware** [comment]
I'll get right on it, gotta check the legality of it first though. Look for it tonight...

**Comment by lightyrs** [comment]
Honestly, @ericvolp12 — as much as I would love a web interface, I feel like that's the kind of thing that can get this project shut down (as SoundCloud is more label-affiliated than ever right now).  Even though the code and forks would still exist, this project is so great it might be more worthwhile to let it live in the shadows.  Just my two cents.

Thank you for a great tool!

**Comment by jakiestfu** [comment]
@fluential (cc @ericvolp12) I think a web interface would be nice, but there are many avenues for such things. I might have to side with @lightyrs.

However, since this project is open source and provides a node API, there is nothing stopping you from creating your own project that implements `otr` in the fashion you want!

**Comment by jazware** [comment]
Okay, well. My node project has been giving me some issues anyhow. I guess I can keep whatever web service might arise a bit more private ;)
